services:
  postgres:
    volumes:
      - postgres:/var/lib/postgresql/data
    image: postgres:alpine
    restart: always
    ports:
      - 54322:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: asan
    
  pgadmin4:
    volumes:
      - pgadmin:/var/lib/pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pass
 
  mongo:
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    image: mongo:jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: asan
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://mongo:password123@mongo:27017/

  minio:
    volumes:
      - minio:/data
    image: minio/minio:latest
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password123
      # MINIO_VOLUMES: /mnt/data
    command: server /data --console-address ":9001"

  kafka:
    volumes:
      - kafka_secrets:/etc/kafka/secrets
      - kafka_config:/mnt/shared/config
      - kafka_data:/var/lib/kafka/data
    image: apache/kafka:latest
    restart: always
    ports:
      - 9092:9092

volumes:
  postgres:
  pgadmin:
  mongo_configdb:
  mongo_db:
  minio:
  kafka_secrets:
  kafka_config:
  kafka_data: